window.luiWalletConfig = {
  sheetUrl: "https://docs.google.com/spreadsheets/d/1FjFrjkNb_7QENGgM4eCU0OnouztzCG6o4yTY7Z60_JQ/edit",
  sheetName: "Septiembre",
  storageKey: "lui-wallet-transactions-sheet-v1",
  settingsKey: "lui-wallet-settings",
  summaryKey: "lui-wallet-summary-sheet-v1",
  savingsGoal: 10000,
  categories: [
    { key: "fixed", label: "Fijos", sheetLabel: "Gastos fijos", icon: "F", accent: "#2f74ff", limit: 7000, description: "Créditos y compromisos base" },
    { key: "necessary", label: "Necesarios", sheetLabel: "Gastos necesarios", icon: "N", accent: "#17d68f", limit: 2500, description: "Salud, comida, gasolina y pendientes" },
    { key: "fun", label: "Pendejos", sheetLabel: "Pendejos", icon: "P", accent: "#ff3f6c", limit: 1200, description: "Antojos, compras impulsivas y extras" },
    { key: "outflow", label: "Salidas", sheetLabel: "Salidas", icon: "S", accent: "#f9c74f", limit: 1000, description: "Parqueo, traslados y pagos pequeños" },
  ],
  initialTransactions: [],
  defaultSummary: {
    month: "Septiembre",
    saldoAlDia: 0,
    totalExpenses: 0,
    totalReceived: 0,
    ahorro: 10000,
    categoryTotals: {
      fixed: 0,
      necessary: 0,
      fun: 0,
      outflow: 0,
    },
    credits: [],
    updatedAt: "",
  },
};
