window.luiWalletConfig = {
  sheetUrl: "https://docs.google.com/spreadsheets/d/TU_SPREADSHEET_ID/edit",
  storageKey: "lui-wallet-transactions",
  settingsKey: "lui-wallet-settings",
  summaryKey: "lui-wallet-summary",
  savingsGoal: 10000,
  categories: [
    { key: "fixed", label: "Fijos", sheetLabel: "Gastos fijos", icon: "F", accent: "#2f74ff", limit: 7000, description: "Créditos y compromisos base" },
    { key: "necessary", label: "Necesarios", sheetLabel: "Gastos necesarios", icon: "N", accent: "#17d68f", limit: 2500, description: "Salud, comida, gasolina y pendientes" },
    { key: "fun", label: "Pendejos", sheetLabel: "Pendejos", icon: "P", accent: "#ff3f6c", limit: 1200, description: "Antojos, compras impulsivas y extras" },
    { key: "outflow", label: "Salidas", sheetLabel: "Salidas", icon: "S", accent: "#f9c74f", limit: 1000, description: "Parqueo, traslados y pagos pequeños" },
  ],
  initialTransactions: [
    { id: "demo-sep-001", date: "2026-09-03", description: "Pago de tarjeta", amount: -820, category: "fixed", account: "Banco", syncState: "synced" },
    { id: "demo-sep-002", date: "2026-09-03", description: "Seguro mensual", amount: -475, category: "fixed", account: "Tarjeta Q", syncState: "synced" },
    { id: "demo-sep-003", date: "2026-09-02", description: "Pago de carro", amount: -5000, category: "fixed", account: "Banco", syncState: "synced" },
    { id: "demo-sep-004", date: "2026-09-02", description: "Supermercado", amount: -640.35, category: "necessary", account: "Debito", syncState: "synced" },
    { id: "demo-sep-005", date: "2026-09-02", description: "Gasolina", amount: -330, category: "necessary", account: "Tarjeta Q", syncState: "synced" },
    { id: "demo-sep-006", date: "2026-09-01", description: "Cafe y snack", amount: -58.5, category: "fun", account: "Debito", syncState: "synced" },
    { id: "demo-sep-007", date: "2026-09-01", description: "Cena casual", amount: -185, category: "fun", account: "Tarjeta Q", syncState: "synced" },
    { id: "demo-sep-008", date: "2026-09-03", description: "Parqueo", amount: -25, category: "outflow", account: "Efectivo", syncState: "synced" },
    { id: "demo-sep-009", date: "2026-09-03", description: "Transferencia", amount: -75, category: "outflow", account: "Banco", syncState: "synced" },
    { id: "demo-sep-010", date: "2026-09-01", description: "Ingreso principal", amount: 16800, category: "income", account: "Ingreso", syncState: "synced" },
    { id: "demo-sep-011", date: "2026-09-01", description: "Proyecto freelance", amount: 4200, category: "income", account: "Ingreso", syncState: "synced" },
  ],
  defaultSummary: {
    month: "Septiembre",
    saldoAlDia: 14500,
    totalExpenses: 6500,
    totalReceived: 21000,
    ahorro: 10000,
    categoryTotals: {
      fixed: 5300,
      necessary: 970.35,
      fun: 243.5,
      outflow: 100,
    },
    credits: [{ name: "Créditos", amount: 5300 }],
    updatedAt: "",
  },
};
